/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "IU520CF",
  "description": "描述: IT技术文档",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/images/logo.png"
      }
    ]
  ],
  "pages": [
    {
      "title": "react",
      "frontmatter": {},
      "regularPath": "/react.html",
      "relativePath": "react.md",
      "key": "v-dafca522",
      "path": "/react.html",
      "headers": [
        {
          "level": 2,
          "title": "react 安装",
          "slug": "react-安装"
        }
      ]
    },
    {
      "title": "next",
      "frontmatter": {},
      "regularPath": "/next.html",
      "relativePath": "next.md",
      "key": "v-25713ad5",
      "path": "/next.html"
    },
    {
      "title": "首页",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-7820564c",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "vue.js",
          "slug": "vue-js"
        },
        {
          "level": 2,
          "title": "vuepress的使用",
          "slug": "vuepress的使用"
        },
        {
          "level": 3,
          "title": "aff",
          "slug": "aff"
        },
        {
          "level": 2,
          "title": "react",
          "slug": "react"
        }
      ]
    },
    {
      "title": "vuepress的使用",
      "frontmatter": {},
      "regularPath": "/vuepress/vuepress.html",
      "relativePath": "vuepress/vuepress.md",
      "key": "v-162aa6dc",
      "path": "/vuepress/vuepress.html",
      "headers": [
        {
          "level": 2,
          "title": "vuepress的使用",
          "slug": "vuepress的使用"
        },
        {
          "level": 3,
          "title": "环境要求",
          "slug": "环境要求"
        },
        {
          "level": 3,
          "title": "安装vuepress",
          "slug": "安装vuepress"
        },
        {
          "level": 3,
          "title": "创建文件夹并进入",
          "slug": "创建文件夹并进入"
        },
        {
          "level": 3,
          "title": "初始化文件",
          "slug": "初始化文件"
        },
        {
          "level": 3,
          "title": "配置启动命令",
          "slug": "配置启动命令"
        },
        {
          "level": 3,
          "title": "基本配置以完成 试着跑起来看看",
          "slug": "基本配置以完成-试着跑起来看看"
        },
        {
          "level": 3,
          "title": "具体使用",
          "slug": "具体使用"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "/images/logo.png",
    "nav": [
      {
        "text": "前端基础",
        "link": "/accumulate/"
      },
      {
        "text": "算法题库",
        "link": "/algorithm/"
      },
      {
        "text": "微博123",
        "link": "https://baidu.com"
      }
    ],
    "sidebar": "auto",
    "sidebarDepth": 2
  }
}